# Generated by Django 2.0 on 2022-02-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cartlist2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartlist2',
        ),
    ]
