# Generated by Django 2.0 on 2022-02-24 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_delete_cartlist2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='cart_id',
            field=models.CharField(default=uuid.uuid1, max_length=200, unique=True),
        ),
    ]
