# Generated by Django 2.0 on 2022-02-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20220224_2244'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
    ]
