# Generated by Django 2.0 on 2022-02-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20220224_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartlist',
            options={},
        ),
        migrations.AlterModelTable(
            name='cartlist',
            table=None,
        ),
    ]
